import {
  mdiChevronDown,
  mdiChevronUp,
  mdiChevronRight,
  mdiChevronLeft,
  mdiMagnify,
  mdiOpenInNew,
  mdiHelpCircleOutline,
  mdiMenu,
  mdiClose,
  mdiEyeOff,
  mdiEye,
  mdiClipboard,
  mdiDownload,
  mdiArrowLeft,
  mdiCheck,
  mdiLoading,
  mdiAlertOutline,
  mdiPlusCircleOutline,
  mdiDelete,
  mdiContentDuplicate,
  mdiPlus,
  mdiExportVariant,
  mdiSend,
  mdiChartAreaspline,
  mdiDotsHorizontal,
  mdiContentCopy,
  mdiFormSelect,
  mdiHistory,
  mdiAutoFix,
  mdiContentSaveAllOutline,
  mdiSendCircle
} from '@mdi/js'

const mdi = new Map<string, string>([
  ['chevron-down', mdiChevronDown],
  ['chevron-up', mdiChevronUp],
  ['chevron-right', mdiChevronRight],
  ['chevron-left', mdiChevronLeft],
  ['magnify', mdiMagnify],
  ['open-in-new', mdiOpenInNew],
  ['help-circle-outline', mdiHelpCircleOutline],
  ['menu', mdiMenu],
  ['close', mdiClose],
  ['eye-closed', mdiEyeOff],
  ['eye', mdiEye],
  ['clipboard', mdiClipboard],
  ['download', mdiDownload],
  ['arrow-left', mdiArrowLeft],
  ['check', mdiCheck],
  ['loading', mdiLoading],
  ['alert', mdiAlertOutline],
  ['plus-circle-outline', mdiPlusCircleOutline],
  ['delete', mdiDelete],
  ['content-duplicate', mdiContentDuplicate],
  ['plus', mdiPlus],
  ['export-variant', mdiExportVariant],
  ['send', mdiSend],
  ['chart', mdiChartAreaspline],
  ['dots-horizontal', mdiDotsHorizontal],
  ['content-copy', mdiContentCopy],
  ['form-select', mdiFormSelect],
  ['history', mdiHistory],
  ['auto-fix', mdiAutoFix],
  ['content-save-all-outline', mdiContentSaveAllOutline],
  ['send-circle', mdiSendCircle]
])

export default mdi
