import {
  mdiChevronDown,
  mdiChevronUp,
  mdiChevronRight,
  mdiMagnify,
  mdiOpenInNew,
  mdiHelpCircleOutline,
  mdiMenu,
  mdiClose,
  mdiEyeOff,
  mdiEye,
  mdiClipboard,
  mdiDownload,
  mdiArrowLeft,
  mdiCheck,
  mdiLoading,
  mdiAlertOutline,
  mdiPlusCircleOutline,
  mdiDelete,
  mdiContentDuplicate,
  mdiPlus,
  mdiExportVariant,
  mdiSend,
  mdiChartAreaspline,
  mdiContentCopy
} from '@mdi/js'

const mdi = new Map<string, string>([
  ['chevron-down', mdiChevronDown],
  ['chevron-up', mdiChevronUp],
  ['chevron-right', mdiChevronRight],
  ['magnify', mdiMagnify],
  ['open-in-new', mdiOpenInNew],
  ['help-circle-outline', mdiHelpCircleOutline],
  ['menu', mdiMenu],
  ['close', mdiClose],
  ['eye-closed', mdiEyeOff],
  ['eye', mdiEye],
  ['clipboard', mdiClipboard],
  ['download', mdiDownload],
  ['arrow-left', mdiArrowLeft],
  ['check', mdiCheck],
  ['loading', mdiLoading],
  ['alert', mdiAlertOutline],
  ['plus-circle-outline', mdiPlusCircleOutline],
  ['delete', mdiDelete],
  ['content-duplicate', mdiContentDuplicate],
  ['plus', mdiPlus],
  ['export-variant', mdiExportVariant],
  ['send', mdiSend],
  ['chart', mdiChartAreaspline],
  ['content-copy', mdiContentCopy]
])

export default mdi
